version: '3.4'

services:
  db:
    image: postgres
    env_file:
      - ./env/db.env

  api:
    build:
      context: ..
      dockerfile: ./prod/Dockerfile
    env_file:
      - ./env/db.env
      - ./env/api.env
    volumes:
      - static_volume:/opt/code/static
      - shm:/dev/shm
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: bash ./scripts/run-with-gunicorn.sh 2

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - static_volume:/opt/code/static
      - shm:/dev/shm
    depends_on:
      - api

  cache:
    image: memcached:1.6.6-alpine

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5462:5462"
      - "15672:15672"

  celery:
    build:
      context: ..
      dockerfile: ./prod/Dockerfile
    env_file:
      - ./env/db.env
      - ./env/api.env
    command: ./scripts/run-celery.sh
    depends_on:
      - db
      - rabbitmq

volumes:
  static_volume:
  shm:
